name: flavor31
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  http: ^0.13.5
  json_serializable: ^6.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

assets:
  - assets/images/location_pin.png
